version: "3.1"
services: 
  db: 
    image: bitnami/mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080